var words = [
  { eng: 'about', tr: 'hemen hemen veya yaklaşık' },
  { eng: 'above', tr: 'üzerine veya yukarısında' },
  { eng: 'across', tr: 'karşıya veya karşı karşıya' },
  { eng: 'action', tr: 'çalışma veya davranış' },
  { eng: 'activity', tr: 'etkinlik veya faaliyet' },
  { eng: 'actor', tr: 'oyuncu veya erkek oyuncu' },
  { eng: 'actress', tr: 'oyuncu veya aktris' },
  { eng: 'add', tr: 'toplamak veya eklemek' },
  { eng: 'address', tr: 'hitap etmek veya adres' },
  { eng: 'adult', tr: 'yetişkin veya er kişi' },
  { eng: 'advice', tr: 'nasihat veya tavsiye' },
  { eng: 'afraid', tr: 'korkmuş veya ürkmüş' },
  { eng: 'after', tr: 'sonra veya öğleden sonra' },
  { eng: 'afternoon', tr: 'öğleden sonra veya son kısım' },
  { eng: 'again', tr: 'bir daha veya tekrar' },
  { eng: 'age', tr: 'yaş veya devir' },
  { eng: 'ago', tr: 'evvel veya önce' },
  { eng: 'agree', tr: 'aynı fikirde olmak veya anlaşmak' },
  { eng: 'air', tr: 'havalandırmak veya hava' },
  { eng: 'airport', tr: 'havalimanı veya hava limanı' },
  { eng: 'all', tr: 'tüm veya hepsi' },
  { eng: 'also', tr: 'ayrıca veya da' },
  { eng: 'always', tr: 'hep veya daima' },
  { eng: 'amazing', tr: 'şaşırtıcı veya hayrete düşürücü' },
  { eng: 'and', tr: 'ile veya ve' },
  { eng: 'angry', tr: 'kızmış veya hiddetli' },
  { eng: 'animal', tr: 'hayvan veya hayvani' },
  { eng: 'another', tr: 'öbür veya ikinci bir' },
  { eng: 'answer', tr: 'yanıt vermek veya cevap vermek' },
  { eng: 'any', tr: 'lalettayin veya her' },
  { eng: 'anyone', tr: 'hiç kimse veya herhangi bir kimse' },
  { eng: 'anything', tr: 'hiçbir şey veya bir şey' },
  { eng: 'apartment', tr: 'daire veya apartman dairesi' },
  { eng: 'apple', tr: 'elma' },
  { eng: 'April', tr: 'nisan veya nisan ayı' },
  { eng: 'area', tr: 'alan veya bölge' },
  { eng: 'arm', tr: 'kol veya destek olmak' },
  { eng: 'around', tr: 'sularında veya etrafında' },
  { eng: 'arrive', tr: 'varmak veya gelip çatmak' },
  { eng: 'art', tr: 'sanat veya maharet' },
  { eng: 'article', tr: 'bent veya madde' },
  { eng: 'artist', tr: 'artist veya sanatçı' },
  { eng: 'as', tr: 'olarak veya dahi' },
  { eng: 'ask', tr: 'soru sormak veya çağırmak' },
  { eng: 'at', tr: 'üzere veya haliyle' },
  { eng: 'August', tr: 'ağustos veya ağustos ayı' },
  { eng: 'aunt', tr: 'hala veya yenge' },
  { eng: 'autumn', tr: 'güz veya hazan' },
  { eng: 'away', tr: 'uzak veya uzakta' },
  { eng: 'baby', tr: 'yavru veya şımartmak' },
  { eng: 'back', tr: 'art veya sırt' },
  { eng: 'bad', tr: 'kötü veya bozuk' },
  { eng: 'bag', tr: 'poşet veya çanta' },
  { eng: 'ball', tr: 'balo veya bilye' },
  { eng: 'banana', tr: 'muz' },
  { eng: 'band', tr: 'bant veya şerit' },
  { eng: 'bank', tr: 'banka veya kümelenmek' },
  { eng: 'bath', tr: 'yıkanmak veya banyo yapmak' },
  { eng: 'bathroom', tr: 'tuvalet veya banyo odası' },
  { eng: 'be', tr: 'bulunmak veya var olmak' },
  { eng: 'beach', tr: 'sahil veya plaj' },
  { eng: 'beautiful', tr: 'güzel veya ahım şahım' },
  { eng: 'because', tr: 'çünkü veya zira' },
  { eng: 'become', tr: 'haline gelmek veya dönüşmek' },
  { eng: 'bed', tr: 'yatak veya oturtmak' },
  { eng: 'bedroom', tr: 'yatak odası veya şebistan' },
  { eng: 'beer', tr: 'bira veya arpasuyu' },
  { eng: 'before', tr: 'evvel veya önce' },
  { eng: 'begin', tr: 'başlatmak veya başlamak' },
  { eng: 'beginning', tr: 'başlangıç veya ilk adım' },
  { eng: 'behind', tr: 'ardındaki veya geriye' },
  { eng: 'believe', tr: 'inanmak veya kanmak' },
  { eng: 'below', tr: 'alttaki veya altta' },
  { eng: 'best', tr: 'en iyi veya baskın çıkmak' },
  { eng: 'better', tr: 'daha iyi veya ıslah etmek' },
  { eng: 'between', tr: 'arasında veya ortada' },
  { eng: 'bicycle', tr: 'bisiklet veya bisikletle gezmek' },
  { eng: 'big', tr: 'iri veya kapı gibi' },
  { eng: 'bike', tr: 'bisiklete binmek veya bisiklet sürmek' },
  { eng: 'bill', tr: 'senet veya ilan etmek' },
  { eng: 'bird', tr: 'kuş veya manita' },
  { eng: 'birthday', tr: 'yaş günü veya doğum günü' },
  { eng: 'black', tr: 'siyahi veya siyah' },
  { eng: 'blog', tr: 'web günlüğü' },
  { eng: 'blonde', tr: 'sarışın veya sarı' },
  { eng: 'blue', tr: 'mavi veya har vurup harman savurmak' },
  { eng: 'boat', tr: 'tekne veya kayık' },
  { eng: 'body', tr: 'ceset veya vücut' },
  { eng: 'book', tr: 'ayırtmak veya deftere işlemek' },
  { eng: 'boot', tr: 'bot veya kovmak' },
  { eng: 'bored', tr: 'sıkılmış veya bıkkın' },
  { eng: 'boring', tr: 'bıktırıcı veya sıkıcı' },
  { eng: 'born', tr: 'doğan veya doğmuş' },
  { eng: 'both', tr: 'her ikisi de veya her ikisi' },
  { eng: 'bottle', tr: 'şişe veya şişelemek' },
  { eng: 'box', tr: 'kutu veya yumruk atmak' },
  { eng: 'boy', tr: 'delikanlı veya oğlan' },
  { eng: 'boyfriend', tr: 'flört veya erkek arkadaş' },
  { eng: 'bread', tr: 'ekmek veya geçim' },
  { eng: 'break', tr: 'kopmak veya bozmak' },
  { eng: 'breakfast', tr: 'kahvaltı veya kahvaltı etmek' },
  { eng: 'bring', tr: 'getirmek veya neden olmak' },
  { eng: 'brother', tr: 'kardeş veya erkek kardeş' },
  { eng: 'brown', tr: 'kahverengi veya karartmak' },
  { eng: 'build', tr: 'inşa etmek veya bina etmek' },
  { eng: 'building', tr: 'inşaat veya yapma' },
  { eng: 'bus', tr: 'otobüs veya otobüsle gitmek' },
  { eng: 'business', tr: 'işletme veya iş kuruluşu' },
  { eng: 'busy', tr: 'işlek veya faal' },
  { eng: 'but', tr: 'ancak veya itiraz' },
  { eng: 'butter', tr: 'tereyağı veya yağ sürmek' },
  { eng: 'buy', tr: 'ısmarlamak veya satın almak' },
  { eng: 'by', tr: 'geçecek biçimde veya evde' },
  { eng: 'bye', tr: 'hoşçakal' },
  { eng: 'cafe', tr: 'kafe veya kahve' },
  { eng: 'cake', tr: 'kek veya kabuklaşmak' },
  { eng: 'call', tr: 'çağırmak veya telefon etmek' },
  { eng: 'camera', tr: 'fotoğraf makinesi veya kamera' },
  { eng: 'can', tr: 'olabilmek veya konservelemek' },
  { eng: 'cannot', tr: 'edememek veya yapamamak' },
  { eng: 'capital', tr: 'sermaye veya başkent' },
  { eng: 'car', tr: 'otomobil veya araba' },
  { eng: 'card', tr: 'kart veya fişlemek' },
  { eng: 'career', tr: 'kariyer veya hız yapmak' },
  { eng: 'carrot', tr: 'kızıl saç veya havuç' },
  { eng: 'carry', tr: 'taşımak veya elde etmek' },
  { eng: 'cat', tr: 'kedi veya kusmak' },
  { eng: 'CD', tr: 'dış çap veya compact disk' },
  { eng: 'cent', tr: 'sent veya metelik' },
  { eng: 'centre', tr: 'merkez veya konsantre olmak' },
  { eng: 'century', tr: 'asır veya yüzyıl' },
  { eng: 'chair', tr: 'koltuk veya iskemle' },
  { eng: 'change', tr: 'değişmek veya değişiklik' },
  { eng: 'chart', tr: 'çizelge veya haritaya almak' },
  { eng: 'cheap', tr: 'ucuz veya değersiz' },
  { eng: 'check', tr: 'denetlemek veya kontrol' },
  { eng: 'cheese', tr: 'peynir veya meyve konservesi' },
  { eng: 'chicken', tr: 'tavuk veya korkak davranmak' },
  { eng: 'child', tr: 'evlat veya ürün' },
  { eng: 'chocolate', tr: 'çikolata veya çikolatadan yapılmış' },
  { eng: 'choose', tr: 'seçmek veya ayırmak' },
  { eng: 'cinema', tr: 'sinema veya sinema salonu' },
  { eng: 'city', tr: 'kent veya metropol' },
  { eng: 'class', tr: 'ders veya saymak' },
  { eng: 'classroom', tr: 'sınıf veya derslik' },
  { eng: 'clean', tr: 'temizlemek veya temizlenmek' },
  { eng: 'climb', tr: 'tırmanmak veya çıkmak' },
  { eng: 'clock', tr: 'saat veya ölçmek' },
  { eng: 'close', tr: 'kapamak veya yakın' },
  { eng: 'clothes', tr: 'giysi veya esvap' },
  { eng: 'club', tr: 'kulüp veya sopa ile dövmek' },
  { eng: 'coat', tr: 'kaplamak veya mont' },
  { eng: 'coffee', tr: 'kahve veya kıraathane' },
  { eng: 'cold', tr: 'soğukluk veya soğukkanlı' },
  { eng: 'college', tr: 'yüksekokul veya üniversite' },
  { eng: 'colour', tr: 'renk veya yüzü kızarmak' },
  { eng: 'come', tr: 'gelmek veya gelip dayanmak' },
  { eng: 'common', tr: 'alışılmış veya yaygın' },
  { eng: 'company', tr: 'bölük veya firma' },
  { eng: 'compare', tr: 'mukayese etmek veya karşılaştırmak' },
  { eng: 'complete', tr: 'tamamlamak veya bütün' },
  { eng: 'computer', tr: 'bilgisayar veya elektronik beyin' },
  { eng: 'concert', tr: 'konser veya birlikte hareket etmek' },
  { eng: 'conversation', tr: 'konuşma veya muhabbet' },
  { eng: 'cook', tr: 'yemek pişirmek veya aşçı' },
  { eng: 'cooking', tr: 'yemek pişirme veya pişim' },
  { eng: 'cool', tr: 'soğutmak veya serin' },
  { eng: 'correct', tr: 'düzeltmek veya haddini bildirmek' },
  { eng: 'cost', tr: 'mal olmak veya ücret' },
  { eng: 'could', tr: '-abilirdi veya -ebilirdi' },
  { eng: 'country', tr: 'yurt veya ülke' },
  { eng: 'course', tr: 'kurs veya rota' },
  { eng: 'cousin', tr: 'kuzen veya amca oğlu' },
  { eng: 'cow', tr: 'inek veya posta koymak' },
  { eng: 'cream', tr: 'kaymak veya krem' },
  { eng: 'create', tr: 'meydana getirmek veya yaratmak' },
  { eng: 'culture', tr: 'kültür veya terbiye' },
  { eng: 'cup', tr: 'kupa veya kavramak' },
  { eng: 'customer', tr: 'müşteri veya tip' },
  { eng: 'cut', tr: 'kesmek veya kesik' },
  { eng: 'dad', tr: 'babacığım veya babacık' },
  { eng: 'dance', tr: 'dans etmek veya sıçramak' },
  { eng: 'dancer', tr: 'dansöz veya rakkase' },
  { eng: 'dancing', tr: 'dans etme veya oynama' },
  { eng: 'dangerous', tr: 'tehlikeli veya riskli' },
  { eng: 'dark', tr: 'karanlık veya belirsizlik' },
  { eng: 'date', tr: '(biriyle) çıkmak veya zaman' },
  { eng: 'daughter', tr: 'kız çocuk veya ilişki' },
  { eng: 'day', tr: 'gün veya gündüz' },
  { eng: 'dear', tr: 'sevgili veya tatlı kimse' },
  { eng: 'December', tr: 'aralık (ayı)' },
  { eng: 'decide', tr: 'karar vermek veya azmetmek' },
  { eng: 'delicious', tr: 'nefis veya lezzetli' },
  { eng: 'describe', tr: 'betimlemek veya tarif etmek' },
  { eng: 'description', tr: 'tasvir veya tarif' },
  { eng: 'design', tr: 'dizayn etmek veya tasarım' },
  { eng: 'desk', tr: 'çalışma masası veya kürsü' },
  { eng: 'detail', tr: 'detay veya ayrıntılı anlatmak' },
  { eng: 'dialogue', tr: 'diyalog veya konuşma' },
  { eng: 'dictionary', tr: 'sözlük veya kamus' },
  { eng: 'die', tr: 'ölmek veya kandilin yağı tükenmek' },
  { eng: 'diet', tr: 'diyet veya perhiz vermek' },
  { eng: 'difference', tr: 'ayrım veya dava' },
  { eng: 'different', tr: 'farklı veya başka' },
  { eng: 'difficult', tr: 'çetin veya zorlu' },
  { eng: 'dinner', tr: 'akşam yemeği veya günün esas yemeği' },
  { eng: 'dirty', tr: 'pisletmek veya kirli' },
  { eng: 'discuss', tr: 'görüşmek veya müzakere etmek' },
  { eng: 'dish', tr: 'tabak veya oymak' },
  { eng: 'do', tr: 'etmek veya yapmak' },
  { eng: 'doctor', tr: 'doktor veya tahrif etmek' },
  { eng: 'dog', tr: 'it veya köpek' },
  { eng: 'dollar', tr: 'amerikan parası veya dolar' },
  { eng: 'door', tr: 'kapı veya eşik' },
  { eng: 'down', tr: 'aşağıya doğru veya alaşağı etmek' },
  { eng: 'downstairs', tr: 'aşağı katta veya alt kat' },
  { eng: 'draw', tr: 'karalamak veya çizmek' },
  { eng: 'dress', tr: 'giyinmek veya giysi' },
  { eng: 'drink', tr: 'içmek veya içki' },
  { eng: 'drive', tr: 'sürmek veya dürtü' },
  { eng: 'driver', tr: 'sürücü veya makinist' },
  { eng: 'during', tr: 'zarfında veya sırasında' },
  { eng: 'DVD', tr: 'dvd' },
  { eng: 'each', tr: 'her biri veya beher' },
  { eng: 'ear', tr: 'kulak veya başaklanmak' },
  { eng: 'early', tr: 'erken veya ilkel' },
  { eng: 'east', tr: 'doğu veya gündoğusu' },
  { eng: 'easy', tr: 'rahat veya basit' },
  { eng: 'eat', tr: 'yemek yemek veya ate' },
  { eng: 'egg', tr: 'yumurta veya tahrik etmek' },
  { eng: 'eight', tr: 'sekiz veya sekiz rakamı' },
  { eng: 'eighteen', tr: 'onsekiz veya on sekiz' },
  { eng: 'eighty', tr: 'seksen veya 80' },
  { eng: 'elephant', tr: 'fil' },
  { eng: 'eleven', tr: 'onbir veya on bir' },
  { eng: 'else', tr: 'başka veya daha' },
  { eng: 'email', tr: 'email göndermek' },
  { eng: 'end', tr: 'sona ermek veya son bulmak' },
  { eng: 'enjoy', tr: 'tadını çıkarmak veya anlamak' },
  { eng: 'enough', tr: 'kafi veya yeter' },
  { eng: 'euro', tr: 'euro veya avro' },
  { eng: 'even', tr: 'düzgün veya pürüzsüz' },
  { eng: 'evening', tr: 'akşam veya son evreler' },
  { eng: 'event', tr: 'olay veya yarışma' },
  { eng: 'ever', tr: 'durmadan veya daima' },
  { eng: 'every', tr: 'her veya alışılmış' },
  { eng: 'everybody', tr: 'cümle alem veya herkes' },
  { eng: 'everyone', tr: 'herkes veya elalem' },
  { eng: 'everything', tr: 'her şey' },
  { eng: 'exam', tr: 'imtihan veya muayene' },
  { eng: 'example', tr: 'örnek veya numune' },
  { eng: 'excited', tr: 'heyecanlı veya coşkulu' },
  { eng: 'exciting', tr: 'heyecanlı veya heyecanlandırma' },
  { eng: 'exercise', tr: 'alıştırma yapmak veya egzersiz' },
  { eng: 'expensive', tr: 'masraflı veya pahalı' },
  { eng: 'explain', tr: 'açıklamak veya izah etmek' },
  { eng: 'extra', tr: 'ekstra veya ilave' },
  { eng: 'eye', tr: 'göz veya süzmek' },
  { eng: 'face', tr: 'yüzleşmek veya yönelmek' },
  { eng: 'fact', tr: 'vaka veya vak’a' },
  { eng: 'fall', tr: 'inmek veya güz' },
  { eng: 'FALSE', tr: 'takma veya sahte' },
  { eng: 'family', tr: 'sülale veya hamile' },
  { eng: 'famous', tr: 'ünlü veya meşhur' },
  { eng: 'fantastic', tr: 'fantastik veya harika' },
  { eng: 'far', tr: 'uzak veya çok fazla' },
  { eng: 'farm', tr: 'çiftlik veya ekip biçmek' },
  { eng: 'farmer', tr: 'çiftçi veya rençper' },
  { eng: 'fast', tr: 'süratli veya hızlı' },
  { eng: 'fat', tr: 'semirtmek veya yağ' },
  { eng: 'father', tr: 'papaz veya baba' },
  { eng: 'favourite', tr: 'gözde veya favori' },
  { eng: 'February', tr: 'şubat veya gücük ay' },
  { eng: 'feel', tr: 'hissetmek veya sezmek' },
  { eng: 'feeling', tr: 'his veya şefkat' },
  { eng: 'festival', tr: 'bayram veya festival' },
  { eng: 'few', tr: 'az veya az miktar' },
  { eng: 'fifteen', tr: 'onbeş veya on beş' },
  { eng: 'fifth', tr: 'beşinci veya beşi' },
  { eng: 'fifty', tr: 'elli veya 50' },
  { eng: 'fill', tr: 'doldurmak veya şişirmek' },
  { eng: 'film', tr: 'film veya filme almak' },
  { eng: 'final', tr: 'final veya kesin' },
  { eng: 'find', tr: 'bulmak veya rastlamak' },
  { eng: 'fine', tr: 'ceza kesmek veya hoş' },
  { eng: 'finish', tr: 'sona ermek veya bitmek' },
  { eng: 'fire', tr: 'ateşlemek veya yangın' },
  { eng: 'first', tr: 'birinci veya önce' },
  { eng: 'fish', tr: 'balık veya avlamak' },
  { eng: 'five', tr: 'beş veya iskambilde beşli' },
  { eng: 'flat', tr: 'düz yüzey veya yassı' },
  { eng: 'flight', tr: 'uçuş veya yağmur' },
  { eng: 'floor', tr: 'kat veya yer' },
  { eng: 'flower', tr: 'çiçek veya çiçeklenmek' },
  { eng: 'fly', tr: 'uçmak veya sinek' },
  { eng: 'follow', tr: 'takip etmek veya kollamak' },
  { eng: 'food', tr: 'besin veya gıda' },
  { eng: 'foot', tr: 'ayak veya çıkarmak' },
  { eng: 'football', tr: 'futbol veya amerikan futbolu' },
  { eng: 'for', tr: 'için veya zarfında' },
  { eng: 'forget', tr: 'unutmak veya ihmal etmek' },
  { eng: 'form', tr: 'biçimlendirmek veya oluşturmak' },
  { eng: 'forty', tr: 'kırk veya 40' },
  { eng: 'four', tr: 'dört veya dört rakamı' },
  { eng: 'fourteen', tr: 'on dört veya XIV' },
  { eng: 'fourth', tr: 'dörtte bir veya dördüncü' },
  { eng: 'free', tr: 'bağımsız veya muaf' },
  { eng: 'Friday', tr: 'cuma veya cuma günü' },
  { eng: 'friend', tr: 'ahbap veya dost' },
  { eng: 'friendly', tr: 'arkadaş canlısı veya cana yakın' },
  { eng: 'from', tr: 'itibaren veya -den' },
  { eng: 'front', tr: 'ön veya cephe' },
  { eng: 'fruit', tr: 'meyve vermek veya meyvelenmek' },
  { eng: 'full', tr: 'tok veya dolu' },
  { eng: 'fun', tr: 'eğlence veya şaka etmek' },
  { eng: 'funny', tr: 'komik veya güldürücü' },
  { eng: 'future', tr: 'istikbal veya gelecek zaman' },
  { eng: 'game', tr: 'oyun veya maç' },
  { eng: 'garden', tr: 'bahçe veya bahçede çalışmak' },
  { eng: 'geography', tr: 'coğrafya' },
  { eng: 'get', tr: 'elde etmek veya kazanmak' },
  { eng: 'girl', tr: 'kız veya kız arkadaş' },
  { eng: 'girlfriend', tr: 'kız arkadaş veya manita' },
  { eng: 'give', tr: 'vermek veya bahşetmek' },
  { eng: 'glass', tr: 'kadeh veya cam' },
  { eng: 'go', tr: 'hareket etmek veya gitmek' },
  { eng: 'good', tr: 'güzel veya iyi' },
  { eng: 'goodbye', tr: 'güle güle veya elveda' },
  { eng: 'grandfather', tr: 'dede veya cet' },
  { eng: 'grandmother', tr: 'babaanne veya nine' },
  { eng: 'grandparent', tr: 'büyükbaba veya büyük ebeveyn' },
  { eng: 'great', tr: 'mükemmel veya harika' },
  { eng: 'green', tr: 'yeşil veya yeşile boyamak' },
  { eng: 'grey', tr: 'ağartmak veya gri' },
  { eng: 'group', tr: 'grup veya toplanmak' },
  { eng: 'grow', tr: 'yetişmek veya büyümek' },
  { eng: 'guess', tr: 'tahmin etmek veya sanmak' },
  { eng: 'guitar', tr: 'gitarist veya gitar' },
  { eng: 'gym', tr: 'spor salonu veya beden eğitimi' },
  { eng: 'hair', tr: 'tüy veya saç' },
  { eng: 'half', tr: 'yarım veya devre' },
  { eng: 'hand', tr: 'el veya uzatmak' },
  { eng: 'happen', tr: 'meydana gelmek veya başından geçmek' },
  { eng: 'happy', tr: 'sevinçli veya çakırkeyif' },
  { eng: 'hard', tr: 'çetin veya zahmetli' },
  { eng: 'hat', tr: 'şapka veya başlık' },
  { eng: 'hate', tr: 'nefret etmek veya kin beslemek' },
  { eng: 'have', tr: 'sahip olmak veya elinde tutmak' },
  { eng: 'have to', tr: 'mecburiyetinde kalmak veya mecbur olmak' },
  { eng: 'he', tr: 'eril o veya kendileri' },
  { eng: 'head', tr: 'kelle veya baş' },
  { eng: 'health', tr: 'sıhhat veya afiyet' },
  { eng: 'healthy', tr: 'sıhhatli veya sağlığa yararlı' },
  { eng: 'hear', tr: 'duymak veya işitmek' },
  { eng: 'hello', tr: 'merhaba veya selam' },
  { eng: 'help', tr: 'yardım etmek veya muavenet etmek' },
  { eng: 'her', tr: 'ona veya ondan' },
  { eng: 'here', tr: 'burada veya burda' },
  { eng: 'hey', tr: 'selam' },
  { eng: 'hi', tr: 'merhaba veya selam' },
  { eng: 'high', tr: 'yüksek veya öfkelenmek' },
  { eng: 'him', tr: 'ona veya onu' },
  { eng: 'his', tr: 'eril onunki veya onun' },
  { eng: 'history', tr: 'geçmiş veya kayıtlar' },
  { eng: 'hobby', tr: 'hobi veya merak' },
  { eng: 'holiday', tr: 'bayram veya tatil yapmak' },
  { eng: 'home', tr: 'ev veya yuvasına dönmek' },
  { eng: 'homework', tr: 'ödev veya ev ödevi' },
  { eng: 'hope', tr: 'ummak veya ümit etmek' },
  { eng: 'horse', tr: 'beygir veya oynamak' },
  { eng: 'hospital', tr: 'hastane veya darülaceze' },
  { eng: 'hot', tr: 'kızgın veya acı' },
  { eng: 'hotel', tr: 'otel' },
  { eng: 'hour', tr: 'saat veya zaman' },
  { eng: 'house', tr: 'ev veya kendi evine almak' },
  { eng: 'how', tr: 'nasıl veya yapma tarzı' },
  { eng: 'however', tr: 'bununla birlikte veya her nasılsa' },
  { eng: 'hundred', tr: 'yüz veya yüz sayısı' },
  { eng: 'hungry', tr: 'acıkmış veya istekli' },
  { eng: 'husband', tr: 'koca veya idareli kullanmak' },
  { eng: 'I', tr: 'ben' },
  { eng: 'Internet', tr: 'internet' },
  { eng: 'ice', tr: 'buz veya buzda soğutmak' },
  { eng: 'ice cream', tr: 'dondurma' },
  { eng: 'idea', tr: 'fikir veya sanı' },
  { eng: 'if', tr: 'eğer veya şart' },
  { eng: 'imagine', tr: 'hayal etmek veya kafasında canlandırmak' },
  { eng: 'important', tr: 'mühim veya gururlu' },
  { eng: 'improve', tr: 'geliştirmek veya ilerletmek' },
  { eng: 'in', tr: 'içeri veya iç' },
  { eng: 'include', tr: 'katmak veya kapsamak' },
  { eng: 'information', tr: 'bilgi veya iddia' },
  { eng: 'interest', tr: 'ilgilendirmek veya faiz' },
  { eng: 'interested', tr: 'alakalı veya hissedar' },
  { eng: 'interesting', tr: 'ilginç veya ilgilenme' },
  { eng: 'interview', tr: 'görüşmek veya mülakat' },
  { eng: 'into', tr: 'içine veya biçimine' },
  { eng: 'introduce', tr: 'tanıtmak veya içeri sokmak' },
  { eng: 'island', tr: 'ada veya adacık' },
  { eng: 'it', tr: 'ona veya ebe' },
  { eng: 'its', tr: 'onun' },
  { eng: 'jacket', tr: 'ceket veya zarf' },
  { eng: 'January', tr: 'ocak' },
  { eng: 'jeans', tr: 'kot veya blucin' },
  { eng: 'job', tr: 'görev veya kiraya vermek' },
  { eng: 'join', tr: 'birleştirmek veya katmak' },
  { eng: 'journey', tr: 'yolculuk veya seyahat' },
  { eng: 'juice', tr: 'meyve suyu veya benzin' },
  { eng: 'July', tr: 'temmuz' },
  { eng: 'June', tr: 'haziran' },
  { eng: 'just', tr: 'sadece veya yalnızca' },
  { eng: 'keep', tr: 'tutmak veya kept' },
  { eng: 'key', tr: 'anahtar veya girmek' },
  { eng: 'kilometre', tr: 'kilometre' },
  { eng: 'kind', tr: 'tür veya cins' },
  { eng: 'kitchen', tr: 'mutfak veya nevale' },
  { eng: 'know', tr: 'bilmek veya tanımak' },
  { eng: 'land', tr: 'karaya ayak basmak veya karaya çıkmak' },
  { eng: 'language', tr: 'lisan veya edebiyat' },
  { eng: 'large', tr: 'iri veya büyük' },
  { eng: 'last', tr: 'sonuncu veya tutunmak' },
  { eng: 'late', tr: 'gecikmiş veya her zamanki' },
  { eng: 'later', tr: 'sonradan veya sonraki' },
  { eng: 'laugh', tr: 'gülmek veya gülüş' },
  { eng: 'learn', tr: 'öğrenmek veya işitmek' },
  { eng: 'leave', tr: 'bırakmak veya terk etmek' },
  { eng: 'left', tr: 'sol veya sol kanat' },
  { eng: 'leg', tr: 'ayak veya koşmak' },
  { eng: 'lesson', tr: 'ders veya hisse' },
  { eng: 'let', tr: 'izin vermek veya vermek' },
  { eng: 'letter', tr: 'mektup veya basmak' },
  { eng: 'library', tr: 'kitaplık veya kütüphane binası' },
  { eng: 'lie', tr: 'yatmak veya yalan söylemek' },
  { eng: 'life', tr: 'yaşam veya can' },
  { eng: 'light', tr: 'aydınlık veya ışık' },
  { eng: 'like', tr: 'beğenmek veya sevmek' },
  { eng: 'line', tr: 'astarlamak veya hat' },
  { eng: 'lion', tr: 'aslan veya başarılı ve aranan kimse' },
  { eng: 'list', tr: 'listelemek veya kaydetmek' },
  { eng: 'listen', tr: 'dinlemek veya kulak asmak' },
  { eng: 'little', tr: 'ufak veya küçük' },
  { eng: 'live', tr: 'yaşamak veya ikamet etmek' },
  { eng: 'local', tr: 'lokal veya yerli' },
  { eng: 'long', tr: 'uzun veya susamak' },
  { eng: 'look', tr: 'bakmak veya bakış' },
  { eng: 'lose', tr: 'kaybetmek veya lost' },
  { eng: 'lot', tr: 'pay veya taksim etmek' },
  { eng: 'love', tr: 'sevmek veya aşk' },
  { eng: 'lunch', tr: 'öğle yemeği veya tümsek' },
  { eng: 'machine', tr: 'makine' },
  { eng: 'magazine', tr: 'fişek haznesi veya mecmua' },
  { eng: 'main', tr: 'esas veya baş' },
  { eng: 'make', tr: 'yapmak veya made' },
  { eng: 'man', tr: 'insan veya erkek' },
  { eng: 'many', tr: 'birçok veya çoğu' },
  { eng: 'map', tr: 'harita veya saptamak' },
  { eng: 'March', tr: 'yürüyüş yapmak veya mart ayı' },
  { eng: 'top', tr: 'tepe veya zirve' },
  { eng: 'total', tr: 'toplam veya külliyat' },
  { eng: 'touch', tr: 'dokunmak veya dokunuş' },
  { eng: 'town', tr: 'kent veya şehir' },
  { eng: 'train', tr: 'eğitmek veya tren' },
  { eng: 'travel', tr: 'gezinmek veya seyahat etmek' },
  { eng: 'tree', tr: 'ağaç' },
  { eng: 'trip', tr: 'gezi veya tökezlemek' },
  { eng: 'true', tr: 'doğru veya hakiki' },
  { eng: 'try', tr: 'denemek veya sınamak' },
  { eng: 'turn', tr: 'çevirmek veya dönmek' },
  { eng: 'TV', tr: 'televizyon' },
  { eng: 'twelve', tr: 'on iki' },
  { eng: 'twenty', tr: 'yirmi' },
  { eng: 'two', tr: 'iki' },
  { eng: 'under', tr: 'altında veya aşağı' },
  { eng: 'understand', tr: 'anlamak veya kavramak' },
  { eng: 'university', tr: 'üniversite' },
  { eng: 'until', tr: 'kadar veya -e dek' },
  { eng: 'up', tr: 'yükseltmek veya yukarı' },
  { eng: 'us', tr: 'biz veya bizim' },
  { eng: 'use', tr: 'kullanmak veya yararlanmak' },
  { eng: 'useful', tr: 'kullanışlı veya faydalı' },
  { eng: 'usually', tr: 'genellikle veya çoğunlukla' },
  { eng: 'vegetable', tr: 'sebze' },
  { eng: 'very', tr: 'çok veya tam' },
  { eng: 'visit', tr: 'ziyaret etmek' },
  { eng: 'wait', tr: 'beklemek veya hizmet etmek' },
  { eng: 'wake', tr: 'uyanmak veya uyandırmak' },
  { eng: 'walk', tr: 'yürüyüş yapmak veya yürümek' },
  { eng: 'wall', tr: 'duvar örmek veya duvar' },
  { eng: 'want', tr: 'istek veya ihtiyaç' },
  { eng: 'warm', tr: 'ısınmak veya ılıtmak' },
  { eng: 'wash', tr: 'yıkanmak veya yıkamak' },
  { eng: 'watch', tr: 'seyretmek veya kol saati' },
  { eng: 'water', tr: 'sulamak veya su' },
  { eng: 'way', tr: 'yol veya rota' },
  { eng: 'we', tr: 'biz' },
  { eng: 'wear', tr: 'giymek veya aşınmak' },
  { eng: 'weather', tr: 'havaya göğüs germek veya hava' },
  { eng: 'website', tr: 'web sitesi' },
  { eng: 'wedding', tr: 'nikah veya düğün' },
  { eng: 'week', tr: 'hafta' },
  { eng: 'weekend', tr: 'hafta sonu' },
  { eng: 'welcome', tr: 'hoş geldiniz demek veya karşılamak' },
  { eng: 'well', tr: 'iyi veya kuyu' },
  { eng: 'west', tr: 'batı' },
  { eng: 'wet', tr: 'ıslatmak veya ıslak' },
  { eng: 'what', tr: 'neyi veya ne' },
  { eng: 'when', tr: 'ne zaman veya -dığı zaman' },
  { eng: 'where', tr: 'neresi veya nereye' },
  { eng: 'which', tr: 'hangi veya hangisi' },
  { eng: 'white', tr: 'beyaz veya beyazlatmak' },
  { eng: 'who', tr: 'kim veya kimki' },
  { eng: 'why', tr: 'neden veya niçin' },
  { eng: 'wife', tr: 'eş veya zevce' },
  { eng: 'will', tr: 'niyet etmek veya vasiyet' },
  { eng: 'win', tr: 'kazanmak veya galip gelmek' },
  { eng: 'window', tr: 'pencere' },
  { eng: 'wine', tr: 'şarap' },
  { eng: 'winter', tr: 'kış' },
  { eng: 'with', tr: 'ile veya beraber' },
  { eng: 'woman', tr: 'kadın' },
  { eng: 'word', tr: 'kelime veya laf' },
  { eng: 'work', tr: 'iş yapmak veya çalışmak' },
  { eng: 'worker', tr: 'işçi veya çalışan' },
  { eng: 'world', tr: 'dünya veya alem' },
  { eng: 'worry', tr: 'endişelenmek veya merak etmek' },
  { eng: 'write', tr: 'yazmak veya kaleme almak' },
  { eng: 'year', tr: 'sene veya yıl' },
  { eng: 'yellow', tr: 'sarı veya sararmak' },
  { eng: 'yes', tr: 'evet' },
  { eng: 'yesterday', tr: 'dün veya geçmiş' },
  { eng: 'you', tr: 'sen veya sizi' },
  { eng: 'young', tr: 'genç veya ufak' },
  { eng: 'your', tr: 'senin' },
  { eng: 'yourself', tr: 'kendin veya kendiniz' },
  { eng: 'my', tr: 'benim' },
  { eng: 'name', tr: 'isim veya ismiyle çağırmak' },
  { eng: 'natural', tr: 'tabii veya natürel' },
  { eng: 'near', tr: 'yakın veya yaklaşmak' },
  { eng: 'need', tr: 'ihtiyaç duymak veya gereksinim' },
  { eng: 'negative', tr: 'negatif veya etkisiz hale getirmek' },
  { eng: 'neighbour', tr: 'komşu veya yaklaşmak' },
  { eng: 'never', tr: 'hiç veya katiyen' },
  { eng: 'new', tr: 'yeni veya değişik' },
  { eng: 'news', tr: 'haber veya bilgi' },
  { eng: 'newspaper', tr: 'gazete' },
  { eng: 'next', tr: 'sonraki veya en bitişik' },
  { eng: 'next to', tr: 'bitişik veya hemen yanındaki' },
  { eng: 'nice', tr: 'sevimli veya hoş' },
  { eng: 'night', tr: 'gece veya karanlık' },
  { eng: 'nine', tr: 'dokuz' },
  { eng: 'nineteen', tr: 'XIX veya on dokuz' },
  { eng: 'ninety', tr: 'doksan' },
  { eng: 'no', tr: 'hayır veya red' },
  { eng: 'no one', tr: 'hiç kimse' },
  { eng: 'nobody', tr: 'hiç kimse veya bir hiç' },
  { eng: 'north', tr: 'kuzey veya şimal' },
  { eng: 'nose', tr: 'burun veya yavaş ilerlemek' },
  { eng: 'not', tr: 'gayri veya asla' },
  { eng: 'note', tr: 'not etmek veya nota' },
  { eng: 'nothing', tr: 'hiç veya önemsiz' },
  { eng: 'November', tr: 'kasım' },
  { eng: 'now', tr: 'şimdi veya derhal' },
  { eng: 'number', tr: 'numaralamak veya sayı' },
  { eng: 'nurse', tr: 'hemşirelik yapmak veya bakıcılık yapmak' },
  { eng: 'object', tr: 'itiraz etmek veya karşı çıkmak' },
  { eng: "o'clock", tr: 'saat' },
  { eng: 'October', tr: 'ekim' },
  { eng: 'of', tr: 'karşı veya hakkında' },
  { eng: 'off', tr: 'kapalı veya kalkmak' },
  { eng: 'office', tr: 'makam veya büro' },
  { eng: 'often', tr: 'sık sık veya sık' },
  { eng: 'oh', tr: 'ey veya ha' },
  { eng: 'OK', tr: 'onaylamak veya kabul etmek' },
  { eng: 'old', tr: 'eskimiş veya eski' },
  { eng: 'on', tr: 'üstünde veya yanmak' },
  { eng: 'once', tr: 'bir kere veya birkez' },
  { eng: 'one', tr: 'bir veya biri' },
  { eng: 'onion', tr: 'soğan' },
  { eng: 'online', tr: 'bağlantılı veya çevrim içi' },
  { eng: 'only', tr: 'tek veya yalnızca' },
  { eng: 'open', tr: 'açılmak veya açık' },
  { eng: 'opinion', tr: 'kanaat veya düşünce' },
  { eng: 'opposite', tr: 'zıt veya karşıt' },
  { eng: 'or', tr: 'ya da veya altın sarısı' },
  { eng: 'orange', tr: 'portakal veya portakalrengi' },
  { eng: 'order', tr: 'sipariş vermek veya buyurmak' },
  { eng: 'other', tr: 'öbür veya başka' },
  { eng: 'our', tr: 'bizim' },
  { eng: 'out', tr: 'çıkış veya dışarı' },
  { eng: 'outside', tr: 'dıştan veya dışarı' },
  { eng: 'over', tr: 'bitmiş veya üstüne' },
  { eng: 'own', tr: 'sahip olmak veya itiraf etmek' },
  { eng: 'page', tr: 'sayfa' },
  { eng: 'paint', tr: 'boyamak veya portresini yapmak' },
  { eng: 'painting', tr: 'tablo veya ressamlık' },
  { eng: 'pair', tr: 'çift veya eşlemek' },
  { eng: 'paper', tr: 'kağıt veya örtbas etmek' },
  { eng: 'paragraph', tr: 'fıkra veya makale' },
  { eng: 'parent', tr: 'ebeveynlik etmek veya soy' },
  { eng: 'park', tr: 'park etmek' },
  { eng: 'part', tr: 'parça veya taraf' },
  { eng: 'partner', tr: 'eş veya ortak etmek' },
  { eng: 'party', tr: 'taraf veya parti yaparak kutlamak' },
  { eng: 'passport', tr: 'geçiş belgesi veya pasaport' },
  { eng: 'past', tr: 'geçmiş' },
  { eng: 'pay', tr: 'ödemek veya ücret' },
  { eng: 'pen', tr: 'kalem veya kaleme almak' },
  { eng: 'pencil', tr: 'kurşunkalem' },
  { eng: 'people', tr: 'insanlar veya halk' },
  { eng: 'pepper', tr: 'biber veya pul biber koymak' },
  { eng: 'perfect', tr: 'kusursuz veya mükemmelleştirmek' },
  { eng: 'period', tr: 'devir veya çağ' },
  { eng: 'person', tr: 'kişi veya kimse' },
  { eng: 'personal', tr: 'kişisel veya şahsi' },
  { eng: 'phone', tr: 'telefon etmek' },
  { eng: 'photo', tr: 'foto veya resim vermek' },
  { eng: 'photograph', tr: 'fotoğraflamak veya fotoğrafını çekmek' },
  { eng: 'phrase', tr: 'ifade etmek veya cümle ile anlatmak' },
  { eng: 'piano', tr: 'piyano veya hafif' },
  { eng: 'picture', tr: 'resim veya resmetmek' },
  { eng: 'piece', tr: 'tane veya yamamak' },
  { eng: 'pig', tr: 'domuz veya yavrulamak' },
  { eng: 'pink', tr: 'pembe veya süngü ile delmek' },
  { eng: 'place', tr: 'koymak veya yerleştirmek' },
  { eng: 'plan', tr: 'planlamak veya plan' },
  { eng: 'plane', tr: 'düzlemek veya düzlem' },
  { eng: 'plant', tr: 'dikmek veya tesis' },
  { eng: 'play', tr: 'oynamak veya piyes' },
  { eng: 'player', tr: 'oyuncu veya sporcu' },
  { eng: 'please', tr: 'memnun etmek veya lütfen' },
  { eng: 'pocket', tr: 'cebe indirmek veya cep' },
  { eng: 'poem', tr: 'şiir' },
  { eng: 'police', tr: 'polis veya korumak' },
  { eng: 'policeman', tr: 'polis memuru' },
  { eng: 'pool', tr: 'gölcük veya havuz' },
  { eng: 'poor', tr: 'zavallı veya kötü' },
  { eng: 'popular', tr: 'meşhur veya popüler' },
  { eng: 'population', tr: 'nüfus' },
  { eng: 'position', tr: 'pozisyon' },
  { eng: 'possible', tr: 'olası veya yapılabilir' },
  { eng: 'post', tr: 'posta veya postalamak' },
  { eng: 'potato', tr: 'patates' },
  { eng: 'pound', tr: 'sterlin veya vuruş' },
  { eng: 'prepare', tr: 'hazırlanmak veya düzmek' },
  { eng: 'present', tr: 'takdim etmek veya sunmak' },
  { eng: 'pretty', tr: 'güzel veya hoş' },
  { eng: 'price', tr: 'paha veya fiyat' },
  { eng: 'problem', tr: 'sorun veya mesele' },
  { eng: 'product', tr: 'ürün veya mahsul' },
  { eng: 'programme', tr: 'programlamak veya program' },
  { eng: 'project', tr: 'tasarlamak veya proje' },
  { eng: 'purple', tr: 'mor veya morarmak' },
  { eng: 'push', tr: 'itelemek veya itiş' },
  { eng: 'put', tr: 'koymak veya atmak' },
  { eng: 'quarter', tr: 'çeyrek' },
  { eng: 'question', tr: 'sorgulamak veya kuşkulanmak' },
  { eng: 'quick', tr: 'çabuk veya çabukça' },
  { eng: 'quiet', tr: 'sakinleştirmek veya sessiz' },
  { eng: 'quite', tr: 'oldukça veya tamamen' },
  { eng: 'radio', tr: 'radyo veya telsiz' },
  { eng: 'rain', tr: 'yağmak veya yağmur' },
  { eng: 'rainy', tr: 'yağmurlu' },
  { eng: 'read', tr: 'okumak veya okumak' },
  { eng: 'reading', tr: 'okuma veya ders' },
  { eng: 'ready', tr: 'hazır veya razı' },
  { eng: 'real', tr: 'gerçek veya sahici' },
  { eng: 'really', tr: 'gerçekten veya sahiden' },
  { eng: 'red', tr: 'kızarmış veya kırmızı' },
  { eng: 'remember', tr: 'hatırlamak veya anmak' },
  { eng: 'repeat', tr: 'tekrar etmek veya yinelemek' },
  { eng: 'rest', tr: 'dinlendirmek veya dinlenmek' },
  { eng: 'restaurant', tr: 'lokanta veya restoran' },
  { eng: 'result', tr: 'netice veya sonuç' },
  { eng: 'return', tr: 'dönmek veya geri vermek' },
  { eng: 'rich', tr: 'zengin veya verimli' },
  { eng: 'ride', tr: 'binmek veya sürmek' },
  { eng: 'right', tr: 'doğru veya sağ' },
  { eng: 'river', tr: 'ırmak veya nehir' },
  { eng: 'road', tr: 'yol veya cadde' },
  { eng: 'room', tr: 'oda veya yer' },
  { eng: 'run', tr: 'çalıştırmak veya koşmak' },
  { eng: 'sad', tr: 'üzgün veya acıklı' },
  { eng: 'salad', tr: 'salata' },
  { eng: 'salt', tr: 'tuz veya salamura etmek' },
  { eng: 'same', tr: 'aynı' },
  { eng: 'sandwich', tr: 'sandviç veya sandviç yapmak' },
  { eng: 'Saturday', tr: 'cumartesi' },
  { eng: 'say', tr: 'demek veya söylemek' },
  { eng: 'school', tr: 'okul veya mektep' },
  { eng: 'science', tr: 'ilim veya bilim' },
  { eng: 'scientist', tr: 'bilim insanı' },
  { eng: 'sea', tr: 'deniz veya umman' },
  { eng: 'second', tr: 'ikinci veya yardım etmek' },
  { eng: 'sentence', tr: 'hüküm vermek veya cümle' },
  { eng: 'September', tr: 'eylül' },
  { eng: 'seven', tr: 'yedi veya yedili' },
  { eng: 'seventeen', tr: 'on yedi veya XVII' },
  { eng: 'seventy', tr: 'yetmiş veya 70' },
  { eng: 'she', tr: 'o veya dişi' },
  { eng: 'ship', tr: 'göndermek veya vapur' },
  { eng: 'shirt', tr: 'gömlek veya futbol forması' },
  { eng: 'shoe', tr: 'ayakkabı veya potin' },
  { eng: 'shop', tr: 'alışveriş etmek veya dükkan' },
  { eng: 'shopping', tr: 'alışveriş' },
  { eng: 'short', tr: 'kısa veya alçak' },
  { eng: 'should', tr: 'meli veya malı' },
  { eng: 'show', tr: 'göstermek veya gösteri' },
  { eng: 'shower', tr: 'duş almak veya sağanak' },
  { eng: 'sick', tr: 'hasta veya marazlı' },
  { eng: 'side', tr: 'yan veya taraf' },
  { eng: 'sign', tr: 'imzalamak veya işaret' },
  { eng: 'simple', tr: 'basit veya sıradan' },
  { eng: 'sing', tr: 'şarkı söylemek veya övmek' },
  { eng: 'singer', tr: 'şarkıcı veya hanende' },
  { eng: 'sister', tr: 'bacı veya rahibe' },
  { eng: 'sit', tr: 'oturmak veya kurulmak' },
  { eng: 'situation', tr: 'durum veya konum' },
  { eng: 'six', tr: 'altı' },
  { eng: 'sixteen', tr: 'XVI veya on altı' },
  { eng: 'sixty', tr: 'altmış veya 60' },
  { eng: 'skirt', tr: 'etrafını sarmak veya etek' },
  { eng: 'sleep', tr: 'uyumak veya yatmak' },
  { eng: 'slow', tr: 'yavaşlatmak veya ağır' },
  { eng: 'small', tr: 'küçük veya ufak' },
  { eng: 'snow', tr: 'kar veya kar yağmak' },
  { eng: 'so', tr: 'demek veya o kadar' },
  { eng: 'some', tr: 'kimi veya bazı' },
  { eng: 'somebody', tr: 'birisi' },
  { eng: 'someone', tr: 'biri veya bir kimse' },
  { eng: 'something', tr: 'birşey veya bilmem ne' },
  { eng: 'sometimes', tr: 'bazen veya bazen' },
  { eng: 'son', tr: 'erkek çocuk veya evlat' },
  { eng: 'song', tr: 'şarkı veya türkü' },
  { eng: 'soon', tr: 'yakında veya erkenden' },
  { eng: 'sorry', tr: 'üzgün veya pişman' },
  { eng: 'soup', tr: 'çorba' },
  { eng: 'south', tr: 'güney veya kıble' },
  { eng: 'space', tr: 'aralık veya boşluk' },
  { eng: 'speak', tr: 'konuşmak veya nutuk çekmek' },
  { eng: 'special', tr: 'özel veya has' },
  { eng: 'spell', tr: 'hecelemek veya tılsım' },
  { eng: 'spend', tr: 'geçirmek veya harcamak' },
  { eng: 'sport', tr: 'spor veya dalga geçmek' },
  { eng: 'spring', tr: 'sıçramak veya yaylanmak' },
  { eng: 'start', tr: 'başlamak veya hareket etmek' },
  { eng: 'station', tr: 'istasyon veya görevlendirmek' },
  { eng: 'stay', tr: 'kalmak veya durmak' },
  { eng: 'still', tr: 'durgun veya halen' },
  { eng: 'stop', tr: 'durdurmak veya durmak' },
  { eng: 'store', tr: 'depolamak veya dükkan' },
  { eng: 'story', tr: 'kat veya hikaye' },
  { eng: 'strange', tr: 'acayip veya garip' },
  { eng: 'street', tr: 'cadde veya sokak' },
  { eng: 'strong', tr: 'kuvvetli veya sıkı' },
  { eng: 'student', tr: 'öğrenci veya bilim insanı' },
  { eng: 'study', tr: 'incelemek veya çalışmak' },
  { eng: 'stupid', tr: 'aptal veya mankafa' },
  { eng: 'subject', tr: 'maruz bırakmak veya bırakmak' },
  { eng: 'succeed', tr: 'başarmak veya ardından gelmek' },
  { eng: 'such', tr: 'çok' },
  { eng: 'sugar', tr: 'şeker veya şeker katmak' },
  { eng: 'summer', tr: 'yaz' },
  { eng: 'sun', tr: 'güneş veya güneşlendirmek' },
  { eng: 'Sunday', tr: 'pazar' },
  { eng: 'supermarket', tr: 'süpermarket' },
  { eng: 'swim', tr: 'yüzmek veya dolmak' },
  { eng: 'swimming', tr: 'yüzme veya yüzmek' },
  { eng: 'table', tr: 'masa veya koymak' },
  { eng: 'take', tr: 'çekmek veya almak' },
  { eng: 'talk', tr: 'konuşmak veya söylev' },
  { eng: 'tall', tr: 'uzun veya uzun boylu' },
  { eng: 'taxi', tr: 'taksi' },
  { eng: 'tea', tr: 'çay' },
  { eng: 'teach', tr: 'öğretmek veya okutmak' },
  { eng: 'teacher', tr: 'hoca veya öğretmen' },
  { eng: 'team', tr: 'takım veya kürek çekmek' },
  { eng: 'telephone', tr: 'telefon etmek veya telefon' },
  { eng: 'television', tr: 'televizyon' },
  { eng: 'tell', tr: 'söylemek veya anlatmak' },
  { eng: 'ten', tr: 'on' },
  { eng: 'tennis', tr: 'tenis' },
  { eng: 'test', tr: 'sınamak veya deneme' },
  { eng: 'than', tr: 'kıyasla veya -den' },
  { eng: 'thank', tr: 'teşekkür etmek' },
  { eng: 'thanks', tr: 'şükran veya teşekkürler' },
  { eng: 'that', tr: 'şu veya o' },
  { eng: 'the', tr: 'belirli tanımlık' },
  { eng: 'their', tr: 'onların' },
  { eng: 'them', tr: 'onları' },
  { eng: 'then', tr: 'şimdi veya demek ki' },
  { eng: 'there', tr: 'orada veya oraya' },
  { eng: 'these', tr: 'bunlar' },
  { eng: 'they', tr: 'onlar' },
  { eng: 'thing', tr: 'şey veya eşya' },
  { eng: 'think', tr: 'düşünmek veya sanmak' },
  { eng: 'third', tr: 'üçte bir veya üçüncü' },
  { eng: 'thirteen', tr: 'on üç veya XIII' },
  { eng: 'thirty', tr: 'otuz veya 30' },
  { eng: 'this', tr: 'bu veya şimdiki' },
  { eng: 'those', tr: 'şunlar veya bunlar' },
  { eng: 'though', tr: 'gerçi veya karşın' },
  { eng: 'three', tr: 'üç' },
  { eng: 'through', tr: 'vasıtasıyla veya bitmiş' },
  { eng: 'time', tr: 'zaman' },
  { eng: 'to', tr: 'karşı veya -e' },
  { eng: 'today', tr: 'bugün veya günümüzde' },
  { eng: 'together', tr: 'birlikte veya ikisi bir arada' },
  { eng: 'tomorrow', tr: 'yarın' },
  { eng: 'tonight', tr: 'bu gece veya bu akşam' },
  { eng: 'too', tr: 'çok veya de' },
  { eng: 'tooth', tr: 'diş' },
  { eng: 'market', tr: 'çarşı veya piyasa' },
  { eng: 'married', tr: 'evli veya başı bağlı' },
  { eng: 'match', tr: 'eşleştirmek veya eşlemek' },
  { eng: 'May', tr: 'mayıs' },
  { eng: 'maybe', tr: 'belki' },
  { eng: 'me', tr: 'ben' },
  { eng: 'meal', tr: 'öğün veya sofra' },
  { eng: 'mean', tr: 'demek istemek veya anlamına gelmek' },
  { eng: 'meaning', tr: 'mana veya anlam' },
  { eng: 'meat', tr: 'et veya öz' },
  { eng: 'meet', tr: 'karşılaşmak veya görüşme yapmak' },
  { eng: 'meeting', tr: 'toplantı veya miting' },
  { eng: 'member', tr: 'üye veya mensup' },
  { eng: 'menu', tr: 'menü' },
  { eng: 'message', tr: 'ileti veya resmi bildiri' },
  { eng: 'metre', tr: 'metre' },
  { eng: 'midnight', tr: 'geceyarısı' },
  { eng: 'mile', tr: 'mil veya mil' },
  { eng: 'milk', tr: 'süt veya faydalanmak' },
  { eng: 'million', tr: 'milyon' },
  { eng: 'minute', tr: 'dakika veya tutanak tutmak' },
  { eng: 'miss', tr: 'ıska geçmek veya kaçırmak' },
  { eng: 'mistake', tr: 'yanılgı veya yanlış' },
  { eng: 'model', tr: 'model veya modellik etmek' },
  { eng: 'modern', tr: 'çağdaş veya modern kimse' },
  { eng: 'moment', tr: 'an veya cevher' },
  { eng: 'Monday', tr: 'pazartesi' },
  { eng: 'money', tr: 'para' },
  { eng: 'month', tr: 'ay' },
  { eng: 'more', tr: 'daha fazla veya fazla şey' },
  { eng: 'morning', tr: 'sabah veya başlama' },
  { eng: 'most', tr: 'en veya en fazlası' },
  { eng: 'mother', tr: 'ana veya anne gibi davranmak' },
  { eng: 'mountain', tr: 'dağ veya cebel' },
  { eng: 'mouse', tr: 'fare veya fare tutmak' },
  { eng: 'mouth', tr: 'ağız veya tane tane söylemek' },
  { eng: 'move', tr: 'kımıldamak veya hareket etmek' },
  { eng: 'movie', tr: 'film veya sinema' },
  { eng: 'much', tr: 'fazla veya çok şey' },
  { eng: 'mum', tr: 'maske ile oynamak veya hanımefendi' },
  { eng: 'museum', tr: 'müze' },
  { eng: 'music', tr: 'müzik veya nağme' },
  { eng: 'must', tr: 'gerekmek' }
];

var currentQuestion = 0;
var score = 0;

// Soruyu ve seçenekleri göster
function showQuestion() {
  var questionElement = document.getElementById('question');
  questionElement.textContent = words[currentQuestion].eng;

  var optionsElement = document.getElementById('options');
  optionsElement.innerHTML = '';

  // Seçenekleri oluştur
  var options = createRandomOptions();
  options.forEach(function (option) {
    var optionElement = document.createElement('div');
    optionElement.textContent = option;
    optionElement.classList.add('option');
    optionElement.addEventListener('click', function () {
      selectOption(this);
    });
    optionsElement.appendChild(optionElement);
  });
}

// Rastgele seçenekleri oluştur
function createRandomOptions() {
  var options = [];
  var indexes = [];

  // Doğru seçeneği ekle
  options.push(words[currentQuestion].tr);

  // Rastgele yanlış seçenekleri ekle
  while (indexes.length < 3) {
    var randomIndex = Math.floor(Math.random() * words.length);
    if (randomIndex !== currentQuestion && !indexes.includes(randomIndex)) {
      indexes.push(randomIndex);
      options.push(words[randomIndex].tr);
    }
  }

  // Seçenekleri karıştır
  options = shuffle(options);

  return options;
}

// Seçeneği işaretle
function selectOption(optionElement) {
  var options = document.getElementsByClassName('option');
  for (var i = 0; i < options.length; i++) {
    options[i].classList.remove('selected');
  }
  optionElement.classList.add('selected');
}

// Cevabı kontrol et
function checkAnswer() {
  var options = document.getElementsByClassName('option');
  var selectedOption = null;
  for (var i = 0; i < options.length; i++) {
    if (options[i].classList.contains('selected')) {
      selectedOption = options[i];
      break;
    }
  }

  var resultElement = document.getElementById('result');
  if (selectedOption === null) {
    resultElement.textContent = 'Lütfen bir seçenek seçin.';
    return;
  }

  var selectedAnswer = selectedOption.textContent;
  var correctAnswer = words[currentQuestion].tr;

  if (selectedAnswer === correctAnswer) {
    resultElement.textContent = 'Doğru!';
    score++;
  } else {
    resultElement.textContent = 'Yanlış! Doğru cevap: ' + correctAnswer;
  }

  // Cevapları devre dışı bırak
  for (var j = 0; j < options.length; j++) {
    options[j].removeEventListener('click', selectOption);
  }

  // Sonraki soru düğmesini göster
  var nextButton = document.getElementById('next-button');
  nextButton.style.display = 'inline-block';
}

// Sonraki soruya geç
function nextQuestion() {
  var resultElement = document.getElementById('result');
  resultElement.textContent = '';

  // Bir sonraki soruyu göster veya oyunu bitir
  currentQuestion++;
  if (currentQuestion < words.length) {
    showQuestion();
  } else {
    showFinalScore();
  }

  // Cevapları yeniden etkinleştir
  var options = document.getElementsByClassName('option');
  for (var i = 0; i < options.length; i++) {
    options[i].addEventListener('click', function () {
      selectOption(this);
    });
  }

  // Sonraki soru düğmesini gizle
  var nextButton = document.getElementById('next-button');
  nextButton.style.display = 'none';
}

// Oyunu bitir ve puanı göster
function showFinalScore() {
  var container = document.getElementsByClassName('container')[0];
  container.innerHTML = '';

  var scoreElement = document.createElement('h2');
  scoreElement.textContent =
    'Oyun Bitti! Puanınız: ' + score + '/' + words.length;
  container.appendChild(scoreElement);
}

// Dizi elemanlarını karıştır
function shuffle(array) {
  var currentIndex = array.length;
  var temporaryValue;
  var randomIndex;

  while (currentIndex !== 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }

  return array;
}

// Oyunu başlat
showQuestion();
